output:
  format: tab
linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - govet
    - ineffassign
    - maligned
    - misspell
    - prealloc
    - scopelint
    - structcheck
    - typecheck
    - unconvert
    - varcheck
